'use client';

import styles from '@/app/legal.module.css';
import { AlertTriangle, Scale, Sparkles, ShieldAlert, FileWarning, PhoneCall, Ban, HelpCircle, CheckCircle, ArrowRight } from 'lucide-react';
import Link from 'next/link';

const points = [
  {
    icon: Scale,
    title: 'VaadaKaro is NOT a Law Firm',
    color: '#ef4444',
    bg: 'rgba(239, 68, 68, 0.08)',
    body: 'VaadaKaro Technologies is a civic-tech and legal-tech platform. We are not a law firm, a legal service provider, or a licensed advocate. We do not provide professional legal representation or representation before any court or authority. Our platform provides informational tools and facilitates complaint workflows.',
  },
  {
    icon: Sparkles,
    title: 'AI Responses are Informational Only',
    color: '#f59e0b',
    bg: 'rgba(245, 158, 11, 0.08)',
    body: 'Responses from our AI Legal Assistant are generated by language models (Google Gemini) and are intended for educational purposes only. They do not constitute legal advice, legal opinion, or professional guidance. You should not act upon AI-generated information without consulting a licensed advocate.',
  },
  {
    icon: ShieldAlert,
    title: 'No Attorney-Client Relationship',
    color: '#3b82f6',
    bg: 'rgba(59, 130, 246, 0.08)',
    body: 'The use of VaadaKaro — including AI queries and document generation — does NOT create an attorney-client relationship between you and VaadaKaro. No confidential relationship beyond what is outlined in our Privacy Policy is established. AI responses are not privileged legal advice.',
  },
  {
    icon: FileWarning,
    title: 'Generated Documents are Draft Templates',
    color: '#8b5cf6',
    bg: 'rgba(139, 92, 246, 0.08)',
    body: 'Legal drafts generated by our platform are starting-point templates to assist your understanding. They are NOT finished legal instruments and have NOT been reviewed by a lawyer. You are responsible for reviewing, editing, and verifying these drafts before using them in any official capacity.',
  },
  {
    icon: HelpCircle,
    title: 'AI may generate Inaccuracies (Hallucinations)',
    color: '#f97316',
    bg: 'rgba(249, 115, 22, 0.08)',
    body: 'AI systems can produce outputs that are factually incorrect, legally outdated, or missing critical jurisdictional nuances. India\'s laws are complex and frequently updated. Always verify the accuracy of AI outputs with the latest statutory documents or a qualified legal professional.',
  },
  {
    icon: Ban,
    title: 'No Guarantee of Legal Success',
    color: '#6b7280',
    bg: 'rgba(107, 114, 128, 0.08)',
    body: 'VaadaKaro does not guarantee government action, authority response, or any specific legal result. Our platform facilitates workflows; we have no control over how any authority, court, or official department chooses to respond to or resolve your complaint.',
  },
  {
    icon: PhoneCall,
    title: 'Emergency & Urgent Situations',
    color: '#dc2626',
    bg: 'rgba(220, 38, 38, 0.08)',
    body: 'VaadaKaro is NOT an emergency response service. If you are in immediate physical danger, facing an arrest, or require urgent legal intervention for a crime in progress, contact the police directly at 100 or 112. Do not wait for an AI response or platform tracking update.',
  },
  {
    icon: CheckCircle,
    title: 'Your Responsibility to Verify',
    color: '#10b981',
    bg: 'rgba(16, 185, 129, 0.08)',
    body: 'By using this platform, you accept sole responsibility for vetting and verifying any information before acting on it. VaadaKaro serves as an enablement tool. The final legal decisions and actions you take are yours alone. We strongly advise professional consultation for complex matters.',
  },
  {
    icon: AlertTriangle,
    title: 'Complex Matters — Consult a Lawyer',
    color: '#d97706',
    bg: 'rgba(217, 119, 6, 0.08)',
    body: 'Complex legal matters — such as criminal defense, family disputes, complex property litigation, and constitutional issues — require professional legal representation. VaadaKaro\'s AI can guide you on basics, but you must hire a licensed advocate for representation.',
  },
];

export default function DisclaimerPage() {
  return (
    <div className={styles.legalPage}>
      {/* Alert Banner */}
      <div style={{ background: '#fef2f2', borderBottom: '1px solid rgba(239,68,68,0.2)', padding: '0.75rem 2rem', textAlign: 'center' }}>
        <p style={{ color: '#b91c1c', fontSize: '0.85rem', fontWeight: 700, margin: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
          <AlertTriangle size={15} /> VaadaKaro is NOT a law firm. AI-generated guidance is informational only. Not a substitute for professional legal advice.
        </p>
      </div>

      <div className={styles.hero}>
        <div className={styles.heroEyebrow}>
          <ShieldAlert size={14} /> Important Notice
        </div>
        <h1 className={styles.heroTitle}>AI & Legal Disclaimer</h1>
        <p className={styles.heroSubtitle}>
          Before using VaadaKaro's AI features, please read and understand these critical limitations. Your safety depends on it.
        </p>
        <div className={styles.heroMeta}>
          <span className={styles.heroMetaItem}><strong>Effective Date:</strong> June 16, 2025</span>
          <span className={styles.heroMetaItem}><strong>Applies To:</strong> All AI features</span>
        </div>
      </div>

      <div className={styles.contentWrapper}>
        {/* Critical Notice */}
        <div className={styles.alertBox + ' ' + styles.alertDanger} style={{ marginBottom: '2rem', borderRadius: '12px', padding: '1.5rem 2rem' }}>
          <AlertTriangle size={24} style={{ flexShrink: 0, marginTop: '2px' }} />
          <div>
            <strong style={{ display: 'block', fontSize: '1rem', marginBottom: '0.5rem' }}>Read This Before Proceeding</strong>
            <p style={{ margin: 0 }}>The following points outline the critical limitations of VaadaKaro's AI systems. By continuing to use AI features, you confirm you have read, understood, and accepted these limitations.</p>
          </div>
        </div>

        {/* Disclaimer Cards */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {points.map((p, i) => {
            const Icon = p.icon;
            return (
              <div key={i} className={styles.sectionCard}>
                <div className={styles.sectionHeader} style={{ cursor: 'default' }}>
                  <div className={styles.sectionIcon} style={{ background: p.bg, color: p.color }}>
                    <Icon size={20} />
                  </div>
                  <div className={styles.sectionTitleGroup}>
                    <div className={styles.sectionNum}>Point {String(i + 1).padStart(2, '0')}</div>
                    <div className={styles.sectionTitle}>{p.title}</div>
                  </div>
                </div>
                <div className={styles.sectionBody} style={{ paddingTop: '0.25rem' }}>
                  <p>{p.body}</p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Summary Box */}
        <div className={styles.highlightBox} style={{ marginTop: '2.5rem', fontSize: '0.95rem', lineHeight: 1.7 }}>
          <strong>In summary:</strong> VaadaKaro provides tools, not representation. AI provides information, not advice. Documents are drafts, not final instruments. For any significant legal matter, please consult a licensed advocate in India.
        </div>

        {/* Emergency Contacts */}
        <div style={{ background: 'white', border: '1px solid #e5e7eb', borderRadius: '16px', padding: '2rem', marginTop: '1.5rem' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 800, color: 'var(--brand-navy)', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <PhoneCall size={18} color="var(--brand-gold)" /> Emergency Contacts — India
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '1rem' }}>
            {[
              { label: 'Police', number: '100' },
              { label: 'Women Helpline', number: '1091' },
              { label: 'Ambulance', number: '108' },
              { label: 'Cyber Crime', number: '1930' },
              { label: 'Child Helpline', number: '1098' },
              { label: 'Legal Aid', number: '15100' },
            ].map(e => (
              <div key={e.label} style={{ background: '#f8f9fc', borderRadius: '10px', padding: '1rem', textAlign: 'center' }}>
                <div style={{ fontSize: '1.5rem', fontWeight: 900, color: 'var(--brand-navy)' }}>{e.number}</div>
                <div style={{ fontSize: '0.8rem', color: '#6b7280', fontWeight: 600, marginTop: '0.25rem' }}>{e.label}</div>
              </div>
            ))}
          </div>
        </div>

        <div className={styles.bottomCta}>
          <h2>Need Real Legal Help?</h2>
          <p>Our AI can help you understand your situation. For complex matters, we're building a lawyer marketplace.</p>
          <Link href="/ai-assistant" className={styles.ctaBtn}>
            Use AI Legal Assistant <ArrowRight size={18} />
          </Link>
        </div>
      </div>
    </div>
  );
}
